FROM resin/%%RESIN_MACHINE_NAME%%-node:8
WORKDIR /usr/src/app
COPY package.json package.json
COPY package-lock.json package-lock.json
RUN JOBS=MAX npm install --production --unsafe-perm
COPY . ./
ENV INITSYSTEM on
CMD ["npm", "start"]
